//******************************************************

//Instituto Federal de São Paulo - Campus Sertãozinho

//Disciplina......: M3LPBD

//Programação de Computadores e Dispositivos Móveis

//Aluno...........: Camila Maria de Oliveira Lima

//******************************************************

package base;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Camila Lima
 */
public class ListaCursos extends javax.swing.JFrame {

    /**
     * Creates new form ListaCursos
     */
    public ListaCursos() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadTable();
         
    }

    private void loadTable(){
   
        String cmd = "SELECT id, name_discipline, workload, course_name, "
                + "number_vacancies,period FROM discipline;";
    
    /*Monta a string de conexão e submetendo no banco retorna os dados*/
        cursos.getColumn("Deletar").setCellRenderer(new ButtonRenderer());
        cursos.getColumn("Deletar").setCellEditor(new ButtonEditor(new JCheckBox()));
        
        DefaultTableModel model = (DefaultTableModel) cursos.getModel();
        try {
            java.sql.Connection con = ConexaoMySQL.getInstance().getConnection();
            ResultSet res = con.createStatement().executeQuery(cmd);
            System.out.println(res);
            while(res.next()){
                Vector data = new Vector();
                data.add(res.getInt("id"));
                data.add(res.getString("name_discipline"));
                data.add(res.getInt("workload"));        
                data.add(res.getString("course_name"));
                data.add(res.getInt("number_vacancies"));
                data.add(res.getString("period"));
                data.add("Deletar"); 
                model.addRow(data);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    };
    /* Através desse metodo vai popular a tabela que lista as disciplinas*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        create = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Cursos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Disciplinas");

        exit.setText("Sair");
        exit.setToolTipText("Sair");
        exit.setName("exit"); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        create.setText("Cadastrar");
        create.setToolTipText("Cadastrar");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        cursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Disciplina", "Carga horaria", "Curso pertencente", "Numero de vagas", "Periodo", "Deletar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursos.setRowHeight(20);
        cursos.setRowMargin(3);
        cursos.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(cursos);
        if (cursos.getColumnModel().getColumnCount() > 0) {
            cursos.getColumnModel().getColumn(0).setMinWidth(0);
            cursos.getColumnModel().getColumn(0).setPreferredWidth(0);
            cursos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {create, exit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(create))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {create, exit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFrame tela_cadastro = new CadastroCurso();
        tela_cadastro.setVisible(true);
        
    }//GEN-LAST:event_createActionPerformed
    /* Através desse botão será aberto o formulário de cadastro*/
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
    /*Botão de saída, fechando assim o aplicativo*//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JTable cursos;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
